-- Packages ensured to be installed by Mason.

return {
	"bashls",
	-- "black",
  -- "buf",
  -- "checkmake",
	"cssls",
	"cssmodules_ls",
	"css_variables",
	"dockerls",
  "docker_compose_language_service",
  -- "emmet-language-server",
	"eslint",
  -- "goimports",
  -- "golangci_lint",
  -- "gomodifytags",
	"gopls",
  -- "hadolint",
	"html",
	"htmx",
	"hyprls",
  -- "isort",
	"jsonls",
	"lua_ls",
  -- "markdownlint",
	"marksman",
	-- "mypy",
	-- "nginx_language_server",
	"pbls",
	-- "prettierd",
	"pyright",
  -- "remark-cli",
	"ruff",
	"rust_analyzer",
  -- "rustfmt",
  -- "rustywind",
	-- "selene",
  -- "shfmt",
	"somesass_ls",
  -- "stylelint",
	-- "stylua",
  -- "sqlfluff",
  "sqls",
	"svelte",
	"tailwindcss",
	"templ",
	"ts_ls",
  -- "yamlfmt",
  -- "yamllint",
	"yamlls",
}
