-- Packages ensured to be installed by Mason.

-- For some reason, some packages are apparently invalid (the ones commented out)
-- despite them actually being there in the Mason list...
-- Man I don't have enough energy to deal with any more of Neovim's weird shit today,
-- so note to future self: just install them manually through the Mason window.

return {
  "bashls",
  -- "black",
  -- "buf",
  -- "checkmake",
  -- "csharpier",
  "cssls",
  "cssmodules_ls",
  "css_variables",
  "dockerls",
  "docker_compose_language_service",
  -- "emmet-language-server",
  "eslint",
  -- "goimports",
  -- "gofumpt",
  -- "gomodifytags",
  "gopls",
  -- "impl",
  -- "hadolint",
  "html",
  "htmx",
  "hyprls",
  -- "isort",
  "jsonls",
  "lua_ls",
  "marksman",
  -- "markdownlint-cli2",
  -- "mypy",
  -- "nginx_language_server",
  "pbls",
  -- "prettierd",
  "pyright",
  -- "remark-cli",
  "ruff",
  "rust_analyzer",
  -- "rustfmt",
  -- "rustywind",
  -- "selene",
  -- "shfmt",
  "somesass_ls",
  -- "stylelint",
  -- "stylua",
  -- "sqlfluff",
  "sqls",
  "svelte",
  "tailwindcss",
  "templ",
  "ts_ls",
  -- "yamlfmt",
  -- "yamllint",
  "yamlls",
}
