[pyprland]
plugins = [
  "layout_center"
  # I wanted to use the scratchpads plugin too but its still kinda shit.
]

[layout_center]
margin = [60, 100]
offset = [0, -10]
next = "movefocus r"
prev = "movefocus l"
next2 = "movefocus d"
prev2 = "movefocus u"

